{{#hibernate}}
# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
# Because detection is disabled you have to set correct dialect by hand.
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  properties.hibernate.temp.use_jdbc_metadata_defaults: false
{{/hibernate}}

server:
  port: 8080
  servlet.context-path: /{{artifact_id}}

management.security.enabled: false

---

spring:
  profiles: local
  {{#hibernate}}datasource:
    driver-class-name: org.postgresql.Driver
    url: {{url}}
    username: {{username}}
    password: {{password}}
  {{/hibernate}}

---

spring:
  profiles: dev
  {{#hibernate}}datasource:
    driver-class-name: org.postgresql.Driver
    url: {{url}}
    username: {{username}}
    password: {{password}}
  {{/hibernate}}

---

spring:
  profiles: qa
  {{#hibernate}}datasource:
    driver-class-name: org.postgresql.Driver
    url: {{url}}
    username: {{username}}
    password: {{password}}
  {{/hibernate}}

---

spring:
  profiles: prod
  {{#hibernate}}datasource:
    driver-class-name: org.postgresql.Driver
    url: {{url}}
    username: {{username}}
    password: {{password}}
  {{/hibernate}}

management.security.enabled: true
